# Generated by Django 2.1.4 on 2019-01-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190107_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hook',
            field=models.IntegerField(null=True),
        ),
    ]
