# Generated by Django 2.1.4 on 2019-01-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medias',
            field=models.TextField(null=True),
        ),
    ]
