# Generated by Django 2.1.4 on 2019-01-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_medias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='medias',
        ),
    ]
