# Generated by Django 2.1.4 on 2019-01-30 07:25

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=videos.models.random_name)),
                ('description', models.TextField(null=True)),
                ('video', models.FileField(upload_to='videos/')),
                ('snap1', models.ImageField(null=True, upload_to='video_snaps/')),
                ('snap2', models.ImageField(null=True, upload_to='video_snaps/')),
                ('snap3', models.ImageField(null=True, upload_to='video_snaps/')),
                ('cover', models.ImageField(null=True, upload_to='video_snaps/')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
