# Generated by Django 2.1.4 on 2019-01-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190105_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_celeb',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_id',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
