# Generated by Django 2.1.4 on 2019-01-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_auto_20190108_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='image',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.ImageField(null=True, upload_to='video_snaps/'),
        ),
        migrations.AddField(
            model_name='video',
            name='snap1',
            field=models.ImageField(null=True, upload_to='video_snaps/'),
        ),
        migrations.AddField(
            model_name='video',
            name='snap2',
            field=models.ImageField(null=True, upload_to='video_snaps/'),
        ),
        migrations.AddField(
            model_name='video',
            name='snap3',
            field=models.ImageField(null=True, upload_to='video_snaps/'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='extension',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='extension',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='image',
            name='memory',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
