# Generated by Django 2.1.4 on 2019-01-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_remove_actual_post_video'),
        ('medias', '0004_auto_20190122_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='post',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
