# Generated by Django 2.1.4 on 2019-01-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0006_auto_20190115_1553'),
        ('medias', '0003_auto_20190116_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medias.Image')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medias.Video')),
            ],
        ),
    ]
