# Generated by Django 2.1.4 on 2019-01-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190115_1553'),
        ('timelines', '0002_auto_20190118_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual_post',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Comment'),
        ),
        migrations.AddField(
            model_name='actual_post',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Like'),
        ),
    ]
