# Generated by Django 2.1.4 on 2019-01-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_auto_20190121_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actual_post',
            name='video',
        ),
    ]
