# Generated by Django 2.1.4 on 2019-02-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190111_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.IntegerField(default=0),
        ),
    ]
